import React from "react";
import Head from "next/head";
import Link from "next/link";
import logo from "../../public/assets/img/Logo.png";
import Image from "next/image";
import bgimg from "../../public/assets/img/Background.png";

const Layout = ({ children, title }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto">
        <div className="banner xl:container px-32 ">
          <header className=" py-10 mb-10">
            <Link href="/">
              <div className="flex justify-center">
                <Image src={logo} />
              </div>
            </Link>
          </header>
          {children}
        </div>
      </main>
    </div>
  );
};

export default Layout;
